apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-engine-config
data:
  JDBC_URL: "jdbc:postgresql://host.minikube.internal:5432/stock_alerts"
  KAFKA_BOOTSTRAP_SERVERS: "host.minikube.internal:9095"
  REDIS_URI: "redis://host.minikube.internal:6379"
  OUTBOX_RELAY_DELAY: "1000"