apiVersion: v1
kind: Service
metadata:
  name: market-data-service
spec:
  selector:
    app: market-data
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data
  template:
    metadata:
      labels:
        app: market-data
    spec:
      containers:
        - name: market-data
          image: market-data-service:v1
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: "k8s"
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  name: market-data-config
                  key: REDIS_URI
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /v1/management/health
              port: 8083
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /v1/management/health
              port: 8083
            initialDelaySeconds: 10