apiVersion: v1
kind: Service
metadata:
  name: price-injector-service
spec:
  selector:
    app: price-injector
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-injector
spec:
  replicas: 1 # Strictly 1 pod
  strategy:
    type: Recreate # Kills the old pod before starting the new one to avoid double injection
  selector:
    matchLabels:
      app: price-injector
  template:
    metadata:
      labels:
        app: price-injector
    spec:
      containers:
        - name: price-injector
          image: price-injector:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: price-injector-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: MARKET_SIMULATOR_DELAY
              valueFrom:
                configMapKeyRef:
                  name: price-injector-config
                  key: MARKET_SIMULATOR_DELAY
          livenessProbe:
            httpGet:
              path: /management/health
              port: 8086
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /management/health
              port: 8086
            initialDelaySeconds: 10